import type { RelaySite, UsageSnapshot } from '../types'

export const defaultSites: RelaySite[] = [
  {
    id: 'demo-relay',
    name: '演示中转站',
    baseUrl: 'https://relay.example.com',
    apiKey: '',
    apiKeyTokenName: '',
    apiKeyProbes: [],
    userId: '',
    cookie: '',
    kind: 'new-api',
    refreshMinutes: 5,
    availabilityProbe: true,
  },
]

const trend = [
  ['00:00', 8, 0.0001, 0, 1, 6, 2],
  ['01:00', 12, 0.0002, 0, 1, 9, 3],
  ['02:00', 10, 0.0002, 0, 1, 8, 2],
  ['03:00', 15, 0.0003, 0, 2, 10, 5],
  ['04:00', 18, 0.0004, 0, 2, 13, 5],
  ['05:00', 16, 0.0003, 0, 2, 12, 4],
  ['06:00', 22, 0.0005, 0, 3, 16, 6],
  ['07:00', 105, 0.0012, 8, 26, 80, 25],
  ['08:00', 5600, 0.0056, 22, 5400, 2090, 3510],
  ['09:00', 27473, 0.0194, 142, 27000, 323, 142],
]

export function createDemoSnapshot(site: RelaySite): UsageSnapshot {
  const defaultTokenName = site.apiKeyTokenName?.trim() || 'demo-primary'

  return {
    generatedAt: new Date().toISOString(),
    mode: 'demo',
    account: {
      currentBalance: 100,
      historicalCost: 12.34,
      requestCount: 128,
      username: 'demo-user',
      group: 'default',
      quotaRaw: 50000000,
      usedQuotaRaw: 6170000,
    },
    summary: {
      realTokens: 27473,
      cost: 0.0194,
      cacheCreation: 142,
      cacheHit: 27000,
      input: 323,
      output: 142,
      cacheHitRate: 0.988,
      totalRequests: 1,
    },
    trends: trend.map(([time, tokens, cost, cacheCreation, cacheHit, input, output]) => ({
      time: `07/02 ${time}`,
      tokens: Number(tokens),
      cost: Number(cost),
      cacheCreation: Number(cacheCreation),
      cacheHit: Number(cacheHit),
      input: Number(input),
      output: Number(output),
    })),
    models: [
      {
        model: 'claude-sonnet-demo',
        group: 'claude',
        tokens: 18540,
        cost: 0.0118,
        input: 1254,
        output: 894,
        cacheCreation: 80,
        cacheHit: 16500,
        requests: 4,
        ratio: 0.15,
      },
      {
        model: 'claude-haiku-demo',
        group: 'claude',
        tokens: 5720,
        cost: 0.0038,
        input: 512,
        output: 256,
        cacheCreation: 32,
        cacheHit: 5200,
        requests: 3,
        ratio: 0.15,
      },
      {
        model: 'gpt-4.1-demo',
        group: 'default',
        tokens: 3584,
        cost: 0.0021,
        input: 2048,
        output: 1536,
        cacheCreation: 20,
        cacheHit: 0,
        requests: 2,
        ratio: 0.15,
      },
      {
        model: 'gpt-4o-mini-demo',
        group: 'default',
        tokens: 1536,
        cost: 0.0006,
        input: 1024,
        output: 512,
        cacheCreation: 10,
        cacheHit: 0,
        requests: 1,
        ratio: 0.2,
      },
    ],
    availability: [
      {
        name: '站点状态',
        endpoint: `${site.baseUrl}/api/status`,
        status: 'ok',
        latencyMs: 186,
        availability: 1,
        detail: '正常',
      },
      {
          name: '兼容模型接口',
        endpoint: `${site.baseUrl}/v1/models`,
        status: 'ok',
        latencyMs: 241,
        availability: 1,
        detail: '模型列表可读',
      },
      {
        name: '管理接口',
        endpoint: `${site.baseUrl}/api/user/self`,
        status: site.apiKey ? 'ok' : 'unknown',
        latencyMs: site.apiKey ? 226 : 0,
        availability: site.apiKey ? 1 : 0,
        detail: site.apiKey ? '鉴权正常' : '等待密钥',
      },
    ],
    groups: [
      { group: 'claude', model: 'claude-sonnet-demo', ratio: 0.15, groupRatio: 0.15, modelRatio: 1, enabled: true },
      { group: 'claude', model: 'claude-haiku-demo', ratio: 0.15, groupRatio: 0.15, modelRatio: 1, enabled: true },
      { group: 'default', model: 'gpt-4.1-demo', ratio: 0.15, groupRatio: 0.15, modelRatio: 1, enabled: true },
      { group: 'default', model: 'gpt-4o-mini-demo', ratio: 0.2, groupRatio: 0.2, modelRatio: 1, enabled: true },
    ],
    tokens: [
      {
        id: 'tok_demo_secondary',
        name: 'demo-secondary',
        status: 'enabled',
        remaining: null,
        used: 18.72,
        group: 'claude',
        models: ['claude-sonnet-demo', 'claude-haiku-demo'],
        keyPreview: 'not returned',
      },
      {
        id: 'tok_demo_primary',
        name: 'demo-primary',
        status: 'enabled',
        remaining: null,
        used: 27.65,
        group: 'default',
        models: ['gpt-4.1-demo', 'gpt-4o-mini-demo'],
        keyPreview: 'not returned',
      },
    ],
    keyChecks: [
        {
          id: 'primary',
          name: defaultTokenName,
          tokenName: defaultTokenName,
        enabled: Boolean(site.apiKey),
        ok: Boolean(site.apiKey),
        status: site.apiKey ? 'ok' : 'optional',
        latencyMs: site.apiKey ? 241 : 0,
        detail: site.apiKey ? '模型列表可读' : '等待 API Key',
        models: site.apiKey ? 2 : 0,
        checkedAt: new Date().toISOString(),
        requests: site.apiKey ? 2 : 0,
        errors: 0,
        tokens: site.apiKey ? 5120 : 0,
        cost: site.apiKey ? 0.0027 : 0,
        avgLatencyMs: site.apiKey ? 2495 : 0,
        successRate: site.apiKey ? 1 : null,
        healthScore: site.apiKey ? 100 : 0,
        healthLabel: site.apiKey ? '健康' : '异常',
        lastUsedAt: site.apiKey ? '2026-07-02 09:00:08' : undefined,
      },
    ],
    logs: [
      ['09:00:10', 'demo-secondary', 'claude-sonnet-demo', 'claude', 1254, 894, 0.0012, 16500, 2350, 'cached'],
      ['09:00:08', 'demo-primary', 'gpt-4.1-demo', 'default', 2048, 1536, 0.0021, 0, 3120, 'success'],
      ['08:59:59', 'demo-secondary', 'claude-haiku-demo', 'claude', 512, 256, 0.0003, 5200, 1080, 'cached'],
      ['08:59:45', 'demo-primary', 'gpt-4o-mini-demo', 'default', 1024, 512, 0.0006, 0, 1870, 'success'],
      ['08:59:33', 'demo-secondary', 'claude-sonnet-demo', 'claude', 1801, 1102, 0.0016, 10500, 2620, 'cached'],
    ].map(([time, tokenName, model, group, input, output, cost, cacheHit, latencyMs, status], index) => ({
      id: `demo_request_${index}`,
      time: `2026-07-02 ${time}`,
      tokenName: String(tokenName),
      model: String(model),
      group: String(group),
      status: status as 'success' | 'error' | 'cached',
      input: Number(input),
      output: Number(output),
      total: Number(input) + Number(output),
      cost: Number(cost),
      cacheCreation: index % 2 === 0 ? 20 : 0,
      cacheHit: Number(cacheHit),
      latencyMs: Number(latencyMs),
      firstTokenMs: Math.max(0, Math.round(Number(latencyMs) * 0.28)),
      ip: `203.0.113.${index + 10}`,
    })),
    sources: [
      { label: '示例数据', endpoint: '本地演示数据', ok: true, kind: 'ok', status: 200, durationMs: 0 },
    ],
    errors: site.apiKey || site.cookie ? [] : ['未配置 API Key 或 Cookie，当前展示为示例数据。'],
  }
}
